"""empty message

Revision ID: 923f55d9529e
Revises: 
Create Date: 2019-11-25 12:53:26.108300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923f55d9529e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aid_institution')
    op.alter_column('contact', 'created_at',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('file', 'created_at',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('file', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('chat_history_media')
    op.drop_table('chat_history')
    op.drop_table('chat_room')
    op.drop_table('welcoming_available')
    op.drop_table('welcoming')
    op.drop_table('user_anonymous')
    op.drop_table('person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('file', 'created_at',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('contact', 'created_at',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_table('aid_institution',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url_site', sa.CHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['contact.id'], name='contact_fkey'),
    sa.ForeignKeyConstraint(['id'], ['file.id'], name='file_fkey'),
    sa.PrimaryKeyConstraint('id', name='aid_institution_pkey')
    )
    op.create_table('chat_room',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('welcoming_available_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_anonymous_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chat_history_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user_anonymous.id'], name='user_anonymous_fkey'),
    sa.ForeignKeyConstraint(['id'], ['welcoming_available.id'], name='welcoming_available_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_room_pkey')
    )
    op.create_table('welcoming',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('welcoming_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['person.id'], name='person_fkey'),
    sa.PrimaryKeyConstraint('id', name='welcoming_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('welcoming_available',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('welcoming_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('on_chat', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['welcoming.id'], name='welcoming_fkey'),
    sa.PrimaryKeyConstraint('id', name='welcoming_available_pkey')
    )
    op.create_table('user_anonymous',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_anonymous_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.CHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_anonymous_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('chat_history_media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_history_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['chat_history.id'], name='chat_history_fkey'),
    sa.ForeignKeyConstraint(['id'], ['file.id'], name='file_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_history_media_pkey')
    )
    op.create_table('chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('welcoming_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_anonymous_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user_anonymous.id'], name='user_anonymous_fkey'),
    sa.ForeignKeyConstraint(['id'], ['welcoming.id'], name='welcoming_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_history_pkey')
    )
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.CHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['contact.id'], name='contact_fkey'),
    sa.ForeignKeyConstraint(['id'], ['file.id'], name='file_fkey'),
    sa.PrimaryKeyConstraint('id', name='person_pkey')
    )
    # ### end Alembic commands ###
